apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasg-backend-deployment
  labels:
    app: tasg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasg-backend
  template:
    metadata:
      labels:
        app: tasg-backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: tasg-backend
          image: gmarinho21/tasg-backend:2d89856
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 500Mi
              ephemeral-storage: 2Gi
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: tasg-backend-secret
                  key: PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tasg-backend-secret
                  key: JWT_SECRET
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tasg-backend-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tasg-backend-secret
                  key: DB_PASSWORD
            - name: DB_PATH
              valueFrom:
                secretKeyRef:
                  name: tasg-backend-secret
                  key: DB_PATH
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tasg-backend-secret
                  key: RESEND_API_KEY
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: tasg-backend-secret
                  key: ENVIRONMENT
